### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by 8mccm8** [krzysiekpiasecki/Gentelella#22]
Hi,

I just installed your sources and the web browser can't find assets (js,css...)

> GET http://dashboard/assets/vendors/bootstrap/dist/css/bootstrap.min.css 
> GET http://dashboard/assets/vendors/font-awesome/css/font-awesome.min.css 404 (Not Found)
> GET http://dashboard/assets/vendors/jquery/dist/jquery.min.js 
> GET http://dashboard/assets/vendors/bootstrap/dist/js/bootstrap.min.js 
> GET http://dashboard/assets/vendors/nprogress/nprogress.js 
> GET http://dashboard/assets/vendors/fastclick/lib/fastclick.js 
> GET http://dashboard/assets/vendors/nprogress/nprogress.js 
> Uncaught ReferenceError: $ is not defined

and in my linux box

> root@SRV:/var/www/dashboard# ls web/assets/
> css  images  js  less

thx

**Comment by krzysiekpiasecki** [comment]
Do you have after installing this app a directory structure like:

```
├── /var/www/dashboard
    ├── web
        ├── assets
            ├── vendor
            ├── css
            ├── images
            ├── js
            ├── less

```

<br>


If ```vendor``` directory is missing, it means that the vendors weren't installed or there was an error during installation.


Try to run the shell command from the root of your application (```/var/www/dashboard```).

```
bower install
```

**Comment by 8mccm8** [comment]
Hi,
as I wrote the structure just after the installation was:

├── /var/www/dashboard
    ├── web
        ├── assets
            ├── css
            ├── images
            ├── js
            ├── less

> If vendor directory is missing, it means that the vendors weren't installed or there was an error during installation.

vendors weren't installed => for sure
there was an error during installation. => nothing printed on my screen... maybe Can I check a log install file?

and for the "bower install" maybe is to late because I pasted the pissing files manually and all is ok now...

**Comment by krzysiekpiasecki** [comment]
I think - it's a problem with installing vendor libraries using ```phing``` in conjunction with ```bower```. 

To check what was wrong you should remove ```/var/www/dashboard/Web/assets/vendor``` libraries and then run shell command ```vendor/bin/phing build --verbose``` to see more verbose output.

**Comment by 8mccm8** [comment]
Hi,

!!!

`root@SRV-SUP:/var/www/dashboard/vendor/bin# ./phing build --verbose
phing [options] [target [target2 [target3] ...]]
Options:
  -h -help               print this message
  -l -list               list available targets in this project
  -v -version            print the version information and exit
  -q -quiet              be extra quiet
  -S -silent             print nothing but task outputs and build failures
  -verbose               be extra verbose
  -debug                 print debugging information
  -emacs, -e             produce logging information without adornments
  -diagnostics           print diagnostics information
  -longtargets           show target descriptions during build
  -logfile <file>        use given file for log
  -logger <classname>    the class which is to perform logging
  -listener <classname>  add an instance of class as a project listener
  -f -buildfile <file>   use given buildfile
  -D<property>=<value>   use value for given property
  -keep-going, -k        execute all targets that do not depend
                         on failed target(s)
  -propertyfile <file>   load all properties from file
  -find <file>           search for buildfile towards the root of the
                         filesystem and use it
  -inputhandler <file>   the class to use to handle user input

Report bugs to <dev@phing.tigris.org>

Unknown argument: --verbose
`

**Comment by krzysiekpiasecki** [comment]
As you see at output verbose argument must be used with one hypen so type argument '-verbose'. By the convention long arguments names are prefixed with double hypen but phing uses single hypen.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: 8mccm8Sent: poniedziałek, 19 września 2016 09:14To: krzysiekpiasecki/GentelellaReply To: krzysiekpiasecki/GentelellaCc: Krzysztof Piasecki; CommentSubject: Re: [krzysiekpiasecki/Gentelella] assets (#22)Hi,

!!!

`root@SRV-SUP:/var/www/dashboard/vendor/bin# ./phing build --verbose
phing [options] [target [target2 [target3] ...]]
Options:
  -h -help               print this message
  -l -list               list available targets in this project
  -v -version            print the version information and exit
  -q -quiet              be extra quiet
  -S -silent             print nothing but task outputs and build failures
  -verbose               be extra verbose
  -debug                 print debugging information
  -emacs, -e             produce logging information without adornments
  -diagnostics           print diagnostics information
  -longtargets           show target descriptions during build
  -logfile         use given file for log
  -logger     the class which is to perform logging
  -listener   add an instance of class as a project listener
  -f -buildfile    use given buildfile
  -D=   use value for given property
  -keep-going, -k        execute all targets that do not depend
                         on failed target(s)
  -propertyfile    load all properties from file
  -find            search for buildfile towards the root of the
                         filesystem and use it
  -inputhandler    the class to use to handle user input

Report bugs to dev@phing.tigris.org

Unknown argument: --verbose
`

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/krzysiekpiasecki/Gentelella","title":"krzysiekpiasecki/Gentelella","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/krzysiekpiasecki/Gentelella"}},"updates":{"snippets":[{"icon":"PERSON","message":"@8mccm8 in #22: Hi,\r\n\r\n!!!\r\n\r\n`root@SRV-SUP:/var/www/dashboard/vendor/bin# ./phing build --verbose\r\nphing [options] [target [target2 [target3] ...]]\r\nOptions:\r\n  -h -help               print this message\r\n  -l -list               list available targets in this project\r\n  -v -version            print the version information and exit\r\n  -q -quiet              be extra quiet\r\n  -S -silent             print nothing but task outputs and build failures\r\n  -verbose               be extra verbose\r\n  -debug                 print debugging information\r\n  -emacs, -e             produce logging information without adornments\r\n  -diagnostics           print diagnostics information\r\n  -longtargets           show target descriptions during build\r\n  -logfile \u003cfile\u003e        use given file for log\r\n  -logger \u003cclassname\u003e    the class which is to perform logging\r\n  -listener \u003cclassname\u003e  add an instance of class as a project listener\r\n  -f -buildfile \u003cfile\u003e   use given buildfile\r\n  -D\u003cproperty\u003e=\u003cvalue\u003e   use value for given property\r\n  -keep-going, -k        execute all targets that do not depend\r\n                         on failed target(s)\r\n  -propertyfile \u003cfile\u003e   load all properties from file\r\n  -find \u003cfile\u003e           search for buildfile towards the root of the\r\n                         filesystem and use it\r\n  -inputhandler \u003cfile\u003e   the class to use to handle user input\r\n\r\nReport bugs to \u003cdev@phing.tigris.org\u003e\r\n\r\nUnknown argument: --verbose\r\n`\r\n"}],"action":{"name":"View Issue","url":"https://github.com/krzysiekpiasecki/Gentelella/issues/22#issuecomment-247924551"}}}

**Comment by 8mccm8** [comment]
yep sorry working on an other stuff...

> ./phing build -verbose
exception 'ConfigurationException' with message 'Buildfile: build.xml does not exist!' in /var/www/dashboard/vendor/phing/phing/classes/phing/Phing.php:552
Stack trace:
#0 /var/www/dashboard/vendor/phing/phing/classes/phing/Phing.php(178): Phing->execute(Array)
#1 /var/www/dashboard/vendor/phing/phing/classes/phing/Phing.php(343): Phing::start(Array, NULL)
#2 /var/www/dashboard/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#3 /var/www/dashboard/vendor/phing/phing/bin/phing(14): require_once('/var/www/dashbo...')
#4 {main}

**Comment by krzysiekpiasecki** [comment]
You should execute phing from the root of your project. Otherwise you must additionally use argument ```-f``` to point the build file.


You may also close this issue if you find it as closed.

**Comment by krzysiekpiasecki** [comment]
Inactive.
