### ISSUE TITLE
Add project to SensioInsightLabs

### ISSUE THREAD

**Issue by krzysiekpiasecki** [krzysiekpiasecki/Gentelella#40]
Parent #39

**Comment by krzysiekpiasecki** [comment]
Start
https://insight.sensiolabs.com/projects/b96214d3-35ed-423a-8275-8dc794de7f96/analyses/2

**Comment by ousamabenyounes** [comment]
Now on each commit you will have a build that will check for lot of interesting point.

One really nice feature, is that it looks on all known security issue, and I got my build down because my twig version was known to have critical security issue.
to fix it I only had to change the twig version from X.XXX to X.XXY ...I Don't have the time to check for all known security issue, but sensioInsight bots can do it for us :)

Once the technical debt removed, you'll also be able to proudly add the sensioInsgiht badge on your project :)

Really happy to see your project on insight. 

It's free for open source projects, but it is really expensive if you have a business / private project. 
This cost is not so expensive when you know what it does :)....

To finish, did you know that phpstorm can be free for open source contributors?

https://www.jetbrains.com/buy/opensource/

I am a yellowlabtools member and I am really proud to use my free open source licence when I work on it...If you didn't know about it you I really recommand you to try.
As I can see, you are the third contributor of Gentellela ...So thank you for your really nice work...with this project you should try to get it...

Really happy to work with Gentellela project contributor Great work Really :)

**Comment by krzysiekpiasecki** [comment]
| To finish, did you know that phpstorm can be free for open source contributors?

I've got own private licence.
